= asciidoc-template-maven-plugin

GitHub support for Asciidoctor on `README.adoc` does not include the `include::` syntax. This plugin reads a templated file and inserts the related markup wherever `inlude::` is found.

--
image::https://www.codefactor.io/repository/github/whelk-io/asciidoc-template-maven-plugin/badge[https://www.codefactor.io/repository/github/whelk-io/asciidoc-template-maven-plugin] 
image::https://api.dependabot.com/badges/status?host=github&repo=whelk-io/flesch-kincaid[https://dependabot.com]
--

== Usage

**given template file**

`src/docs/README.adoc`

```
= Some File

include::otherFile.adoc

= Footer
```

**and include file**

`src/docs/otherFile.adoc`
```
== Other File

Other documentation
```

**when running asciidoc-template**

`mvn asciidoc-template::build`

**then output file contains**

`./README.adoc`

```
= Some File

== Other File

Other documentation

= Footer
```

== Maven Configuration

=== Basic

```xml
<plugin>
	<groupId>io.whelk.asciidoc</groupId>
	<artifactId>asciidoc-template-maven-plugin</artifactId>
</plugin>
```

=== Full

```xml
<plugin>
	<groupId>io.whelk.asciidoc</groupId>
	<artifactId>asciidoc-template-maven-plugin</artifactId>
	<configuration>
		<templateDirectory>src/docs</templateDirectory>
		<templateFile>README.adoc</templateFile>
		<outputDirectory>./</outputDirectory>
		<outputFile>README.adoc</outputFile>
	</configuration>
</plugin>
```

==== Configuration

|===
|`templateDirectory`|Directory to find template asiidocs (.adoc). Defaults to `src/docs`
|`templateFile`|Root file to compile into asciidoc. Defaults to `README.adoc`
|`outputDirectory`|Directory to write compiled asciidoc. Defaults to `./`
|`outputFile`|Output of `templateFile`. Defaults to `templateFile`
|===
