name: pre-release

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Run Unit Tests
        run: ./mvnw -B test
