name: release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Run Unit Tests
        run: ./mvnw -B test

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v12
        with:
          servers: '[{ "id": "ossrh", "username": "${{ secrets.OSSRH_USERNAME }}", "password": "${{ secrets.OSSRH_PASSWORD }}" }]'
          repositories: '[{ "id": "ossrh", "name": "ossrh", "url": "https://oss.sonatype.org/service/local/staging/deploy/maven2/", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } }]'

      - name: Publish package
        run: ./mvnw -B deploy -s settings.xml


        